# Project: C-19 Predictor & Vaccination Center
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Human.o Citizen.o Medical_Staff.o Log_Sign.o DecisionTree.o Inventory.o Centers.o Menu.o
LINKOBJ  = main.o Human.o Citizen.o Medical_Staff.o Log_Sign.o DecisionTree.o Inventory.o Centers.o Menu.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "C-19 Predictor _ Vaccination Center.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Human.o: Human.cpp
	$(CPP) -c Human.cpp -o Human.o $(CXXFLAGS)

Citizen.o: Citizen.cpp
	$(CPP) -c Citizen.cpp -o Citizen.o $(CXXFLAGS)

Medical_Staff.o: Medical_Staff.cpp
	$(CPP) -c Medical_Staff.cpp -o Medical_Staff.o $(CXXFLAGS)

Log_Sign.o: Log_Sign.cpp
	$(CPP) -c Log_Sign.cpp -o Log_Sign.o $(CXXFLAGS)

DecisionTree.o: DecisionTree.cpp
	$(CPP) -c DecisionTree.cpp -o DecisionTree.o $(CXXFLAGS)

Inventory.o: Inventory.cpp
	$(CPP) -c Inventory.cpp -o Inventory.o $(CXXFLAGS)

Centers.o: Centers.cpp
	$(CPP) -c Centers.cpp -o Centers.o $(CXXFLAGS)

Menu.o: Menu.cpp
	$(CPP) -c Menu.cpp -o Menu.o $(CXXFLAGS)
